Repository betagouv/analyse-flux-insertion, pull requests merged in 2021-05, with the labels that each got.

#49 feat(identifier): Identify new applicants with new rules
  components/NewApplicantsRules.js
  components/NewApplicantsRules.module.css
  components/fileHandler.js
  lib/dates.js
  lib/readers/FluxBeneficiaireReader.js
  lib/readers/FluxInstructionReader.js
  lib/reducerFactory.js
  lib/sumPartitions.js
  models/Applicant.js
  models/Application.js
  models/BaseFlux.js
  models/FluxBeneficiaire.js
  models/FluxInstruction.js
  pages/experimentations/ardennes/index.js
  pages/identification-beneficiaires/index.js
  pages/lecteur/cnaf/beneficiaire/index.js
  pages/lecteur/cnaf/instruction/index.js
  public/new_applicants_rules.png
  styles/Home.module.css
Labels: enhancement, refactor

#57 feat(identificateur): Add Category information to new applicants #55
  components/NewApplicantsRules.js
  models/Applicant.js
  models/BaseFlux.js
  models/FluxBeneficiaire.js
  models/FluxInstruction.js
  pages/identification-beneficiaires/index.js
  public/new_applicants_rules.png
Labels: enhancement

#58 feat(identificateur): Add flux instruction file name
  models/Applicant.js
  pages/identification-beneficiaires/index.js
  styles/Home.module.css
Labels: bug, enhancement

#59 enhancement/add_wrong_organization_error_message
  pages/experimentations/ardennes/index.js
Labels: enhancement

#60 feat(lecteur): Add stats to flux instruction
  lib/partitionsHelper.js
  lib/sumPartitions.js
  models/Applicant.js
  models/FluxBeneficiaire.js
  models/FluxInstruction.js
  pages/lecteur/cnaf/beneficiaire/index.js
  pages/lecteur/cnaf/instruction/index.js
  styles/Home.module.css
Labels: enhancement

#66 Changement de l'url de prod oour RDV-Solidarités
  .env.production
Labels: bug

#68 Changements de front pour Ardennes
  pages/experimentations/ardennes-demo/index.js
  pages/experimentations/ardennes/index.js
Labels: enhancement

#70 bug/Correction du bug d'affichage après filtrage des lignes vides
  pages/experimentations/ardennes-demo/index.js
Labels: bug

#69 feat(ops): Make staging to prod transitions easy
  README.md
  apply_changes_to_production_pages.sh
  package.json
  pages/experimentations/ardennes-demo/index.js
  pages/experimentations/ardennes/index.js
Labels: enhancement

#72 Correction de bug pour Ardennes
  pages/experimentations/ardennes-demo/index.js
Labels: bug

#76 feat(identifieur): Identify in monthly flux
  components/NewApplicantsRules/Mensuel.js
  components/NewApplicantsRules/NewApplicantsRules.module.css
  components/NewApplicantsRules/Quotidien.js
  components/fileHandler.js
  models/FluxBeneficiaire.js
  pages/identification-beneficiaires/flux-mensuels/index.js
  pages/identification-beneficiaires/flux-quotidiens/index.js
  pages/identification-beneficiaires/index.js
Labels: enhancement

#61 Ajout de la prise en charge des utilisateurs sans email
  pages/experimentations/ardennes-demo/index.js
Labels: enhancement

#78 Correction de bugs pour Ardennes
  pages/experimentations/ardennes-demo/index.js
Labels: bug
