Repository betagouv/analyse-flux-insertion, pull requests merged in 2021-04, with the labels that each got.

#33 Résolution du bug des fichiers volumineux
  pages/lecteur/cnaf/beneficiaire/index.js
  pages/lecteur/cnaf/index.js
Labels: bug

#47 fix(lecteur): Handle large files processing
  lib/readers/BaseFluxReader.js
  lib/readers/FluxBeneficiaireReader.js
  lib/readers/FluxInstructionReader.js
  lib/reducerFactory.js
  pages/lecteur/cnaf/beneficiaire/index.js
Labels: bug, enhancement

#48 refactor(lecteur): Process batches of applications in large files
  pages/lecteur/cnaf/beneficiaire/index.js
Labels: refactor
